local Lib = loadstring(game:HttpGet("https://raw.githubusercontent.com/NightFallScript/Scripts/refs/heads/main/Key%20System%20and%20Loader%20LIB"))()

local myLib = Lib.new({
    Title = "Bullet.lua",
    Discord = "https://discord.gg/ZKQQne6BNJ",
    KeyURL = "https://raw.githubusercontent.com/NightFallScript/Unicore/refs/heads/main/key"
})

myLib:AddCard(
    "Apocalypse Rising 2",
    "rbxassetid://109672025661691",
    {
        Subtitle = "Expires in -- days", 
        Build = "v2.6",
        Updated = "01.06.2026",
        Status = "Ready To Launch"
    }, 
    "https://raw.githubusercontent.com/NightFallScript/Scripts/refs/heads/main/Apocalypse%20Rising%202" 
)

myLib:AddCard(
    "Project Delta",
    "rbxassetid://86014429821843",
    {
        Subtitle = "Expires in -- days", 
        Build = "v2.0",
        Updated = "01.06.2026",
        Status = "Ready To Launch"
    }, 
    "https://raw.githubusercontent.com/NightFallScript/Scripts/refs/heads/main/Project%20Delta" 
)
